{
  "success": true,
  "date_range": {
    "start": "2025-04-28T00:00:00+00:00",
    "end": "2025-05-03T13:10:50.419361+00:00"
  },
  "summary": {
    "total_tickets": 8,
    "resolved_tickets": 1,
    "open_tickets": 7
  },
  "ticket_breakdown": [
    {
      "category": "os:windows",
      "received": 3,
      "resolved": 1,
      "pending": 2
    },
    {
      "category": "app:desktop application",
      "received": 8,
      "resolved": 1,
      "pending": 7
    },
    {
      "category": "status:triaged",
      "received": 6,
      "resolved": 0,
      "pending": 6
    },
    {
      "category": "bug",
      "received": 7,
      "resolved": 1,
      "pending": 6
    },
    {
      "category": "os:linux",
      "received": 3,
      "resolved": 0,
      "pending": 3
    },
    {
      "category": "app:visual studio",
      "received": 1,
      "resolved": 0,
      "pending": 1
    },
    {
      "category": "status:new",
      "received": 1,
      "resolved": 1,
      "pending": 0
    },
    {
      "category": "app:vs code",
      "received": 1,
      "resolved": 1,
      "pending": 0
    },
    {
      "category": "app:web extension",
      "received": 1,
      "resolved": 1,
      "pending": 0
    },
    {
      "category": "os:macos",
      "received": 1,
      "resolved": 0,
      "pending": 1
    },
    {
      "category": "app:pieces copilot module",
      "received": 1,
      "resolved": 0,
      "pending": 1
    },
    {
      "category": "app:pieces os",
      "received": 1,
      "resolved": 0,
      "pending": 1
    }
  ],
  "most_active_tickets": [
    {
      "number": 702,
      "title": "I'm unable to do Handshake with asana",
      "activity_level": 6.5
    },
    {
      "number": 701,
      "title": "Copilot not responding",
      "activity_level": 4.74
    },
    {
      "number": 691,
      "title": "OS: login does not work ( /os/sign_in HTTP 500)",
      "activity_level": 4.2
    },
    {
      "number": 700,
      "title": "Issues with local llm models",
      "activity_level": 3.88
    },
    {
      "number": 697,
      "title": "Visual Studio 2022 extension interfering with Diagnostic tool output",
      "activity_level": 3.74
    },
    {
      "number": 641,
      "title": "Invalid port http://0.0.0.0:null/connect",
      "activity_level": 2.94
    },
    {
      "number": 584,
      "title": "Copilot is not giving any feedback",
      "activity_level": 2.84
    },
    {
      "number": 459,
      "title": "Bug: unable to cancel the download of an LLLM",
      "activity_level": 2.5
    }
  ],
  "common_issues": [
    {
      "title": "Pieces OS and Integrations Failing",
      "description": "Users report various failures in Pieces OS and integrations like Asana and Copilot. Issues include Handshake failures with Asana, login failures with a 500 error on /os/sign_in, and Copilot unresponsiveness despite conversation summaries updating.  Suggested troubleshooting includes checking logs for errors, ensuring valid model versions, and verifying network connectivity.",
      "frequency": 3,
      "related_issues": [
        {
          "id": 702,
          "title": "I'm unable to do Handshake with asana",
          "text": "I'm unable to do Handshake with asana\n### Checked for Existing Issues?\n\n- [x] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nWindows\n\n### Your Pieces OS Version\n\nLatest Version from Github\n\n### Early Access Program\n\n- [x] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nSee I'm trying to create a handshake with asana But getting error that failed to do handshake , Here Is my code import {\n  createTrigger,\n  TriggerStrategy,\n  type OAuth2PropertyValue,\n  WebhookHandshakeStrategy,\n} from '@activepieces/pieces-framework';\n\nimport { asanaCommon, callAsanaApi, callWebhookApi } from '../common';\nimport { HttpMethod } from '@activepieces/pieces-common';\nimport { asanaAuth } from '../../index';\n\nexport const projectTaskActivity = createTrigger({\n  name: 'project_task_activity',\n  displayName: 'Any Task Activity in Project',\n  description: 'Triggers when any task is added, updated, removed, or deleted in a selected project.',\n  auth: asanaAuth,\n  type: TriggerStrategy.WEBHOOK,\n\n \n\n  props: {\n    workspace: asanaCommon.workspace,\n    project: asanaCommon.project,\n  },\n\n  sampleData: {\n    events: [\n      {\n        user: { gid: '12345', resource_type: 'user', name: 'John Doe' },\n        created_at: '2023-05-15T15:00:00.000Z',\n        action: 'added',\n        resource: { gid: '67890', resource_type: 'task', name: 'Complete project documentation' },\n        parent: { gid: '54321', resource_type: 'project', name: 'Marketing Campaign' },\n      },\n    ],\n  },\n\n \n\n  async onEnable({ propsValue, auth, webhookUrl, store }) {\n    const projectId = propsValue.project;\n    const accessToken = (auth as OAuth2PropertyValue).access_token;\n\n    console.log('[Enable] Creating webhook for project:', projectId, 'Webhook URL:', webhookUrl);\n\n    try {\n      const response = await callWebhookApi(\n        HttpMethod.POST,\n        'webhooks',\n        accessToken,\n        {\n          resource: '1210132224773890',\n          target:webhookUrl,\n          filters: [\n            {\n              resource_type: 'task',\n              action: 'added',\n            },\n            {\n              resource_type: 'task',\n              action: 'changed'\n            }\n          ]\n        }\n      );\n      const webhookId = response.body?.data?.gid;\n      if (!webhookId) {\n        throw new Error('[Enable] Asana webhook creation succeeded but no webhook ID was returned.');\n      }\n\n      await store.put('asana_webhook_gid', webhookId);\n      console.log(`[Enable] Asana webhook created successfully: ${webhookId}`);\n    } catch (err) {\n      console.error('[Enable] Failed to create Asana webhook:', err);\n      // throw err;\n    }\n  },\n\n  async onDisable({ auth, store }) {\n    const accessToken = (auth as OAuth2PropertyValue).access_token;\n    const webhookId = await store.get('asana_webhook_gid');\n\n    // if (!webhookId) {\n    //   console.warn('[Disable] No stored webhook ID found.');\n    //   return;\n    // }\n\n    // try {\n    //   await callAsanaApi(HttpMethod.DELETE, `webhooks/${webhookId}`, accessToken, undefined);\n    //   console.log(`[Disable] Deleted Asana webhook: ${webhookId}`);\n    // } catch (err) {\n    //   console.error(`[Disable] Failed to delete Asana webhook (${webhookId}):`, err);\n    // }\n  },\n\n  async run({ payload }) {\n    console.log('[Run] Received headers:', payload.headers);\n    console.log('[Run] Received body:', payload.body);\n\n    const secret = payload.headers?.['x-hook-secret'];\n    console.log(secret,\"secret for asana is here\")\n    if (secret) {\n      return [{ 'x-hook-secret': secret }];\n    }\n\n    return [payload.body];\n  },\n  handshakeConfiguration: {\n    strategy: WebhookHandshakeStrategy.HEADER_PRESENT,\n    paramName: 'x-hook-secret',\n  },\n  async onHandshake(context) {\n    const secret = context.payload.headers?.['x-hook-secret'];\n    \n    if (!secret) {\n      console.error('[Handshake Error] Missing x-hook-secret header:', context.payload.headers);\n      return {\n        status: 400,\n        body: 'Missing x-hook-secret',\n      };\n    }\n  \n    console.log('[Handshake] Responding with x-hook-secret:', secret);\n  \n    return {\n      status: 200,\n      headers: {\n        'X-Hook-Secret': context.payload.headers?.['x-hook-secret'] // Fixed header name and value\n      },\n      // body: {} // Add empty body\n    };\n  },\n});\n\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 6.5
        },
        {
          "id": 691,
          "title": "OS: login does not work ( /os/sign_in HTTP 500)",
          "text": "OS: login does not work ( /os/sign_in HTTP 500)\n### Checked for Existing Issues?\n\n- [x] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application, Pieces OS\n\n### Operating System / Platform\n\nLinux\n\n### Your Pieces OS Version\n\n11.3.3\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nWhen I try to log in via PFD, the spinner loads indefinitely before opening an error page in the browser:\n\nhttps://pieces.app/authentication-error?sentry_id=00000000000000000000000000000000&os=bb009f04-7e79-44cb-8376-aba647cd2c98&platform=linux\n\nIn the OS logs (Documents/com.pieces.os/Support/logs) I see this entry:\n\n```\n[D]  2025-04-17T15:53:02.391819  0:00:01.425625 POST    [500] /os/sign_in: port:39300\n```\n\nIt is surrounded by HTTP 200s like this:\n\n```\n[D]  2025-04-17T15:52:53.075570  0:00:00.000685 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:52:54.038635  0:00:00.001700 POST    [200] /websites/exists: port:39300\n[D]  2025-04-17T15:52:54.043187  0:00:00.000732 GET     [200] /.well-known/version: port:39300\n[D]  2025-04-17T15:52:54.335453  0:00:00.001876 POST    [200] /websites/exists: port:39300\n[D]  2025-04-17T15:52:56.077590  0:00:00.000695 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:52:59.079649  0:00:00.000662 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:53:02.081551  0:00:00.000486 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:53:02.391819  0:00:01.425625 POST    [500] /os/sign_in: port:39300\n[D]  2025-04-17T15:53:04.272493  0:00:00.001839 POST    [200] /websites/exists: port:39300\n[D]  2025-04-17T15:53:04.334258  0:00:00.000938 GET     [200] /.well-known/version: port:39300\n[D]  2025-04-17T15:53:04.457128  0:00:00.001378 POST    [200] /websites/exists: port:39300\n[D]  2025-04-17T15:53:05.083569  0:00:00.000541 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:53:08.085902  0:00:00.000518 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:53:08.094713  0:00:00.001812 POST    [200] /websites/exists: port:39300\n```\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 4.2
        },
        {
          "id": 701,
          "title": "Copilot not responding",
          "text": "Copilot not responding\n### Checked for Existing Issues?\n\n- [x] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nWindows\n\n### Your Pieces OS Version\n\nPiecesOS: 11.3.3 - Pieces for Developers: 4.1.1\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nHey all,\nPieces Copilot no longer responds in conversations in the app, or through any of the extensions (VS Code/Chrome). It just keeps loading. I've tried hard-resetting, restarting, reinstalling, On-Device LLMs, and Cloud LLMs. The weird thing is, some of the conversations will have a summary or will update the name of the conversation, but it never responds in the chat. I looked at the logs and saw repeated Sentry Event Errors, but not sure what to do with that.  I attached the log file from the day before yesterday (yesterday's is too large and won't upload). What should I do?\n\nThanks!\n\n[log-04292025.txt](https://github.com/user-attachments/files/19997109/log-04292025.txt)\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 4.74
        }
      ]
    },
    {
      "title": "Local and Cloud LLM Model Issues",
      "description": "Users are experiencing issues with both locally hosted and cloud-based LLMs.  Symptoms include failure to install local models, Copilot unresponsiveness, and continuous loading.  A common error message points to a 404 for the Gemini Pro model.  Suggested solutions include verifying model access, checking network connectivity, and ensuring the Pieces app is up-to-date.",
      "frequency": 3,
      "related_issues": [
        {
          "id": 700,
          "title": "Issues with local llm models",
          "text": "Issues with local llm models\n### Checked for Existing Issues?\n\n- [ ] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nLinux\n\n### Your Pieces OS Version\n\n11.3.3\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\n![Image](https://github.com/user-attachments/assets/5a5358da-6109-41e2-8ae0-8e2c50e9a2b6)\n\nPieces will not let me install locally hosted models.\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 3.88
        },
        {
          "id": 584,
          "title": "Copilot is not giving any feedback",
          "text": "Copilot is not giving any feedback\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nmacOS\n\n### Your Pieces OS Version\n\nPieces for Developers 3.3.3\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nThe copilot is not generating anything, it just keeps on loading.\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 2.84
        },
        {
          "id": 701,
          "title": "Copilot not responding",
          "text": "Copilot not responding\n### Checked for Existing Issues?\n\n- [x] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nWindows\n\n### Your Pieces OS Version\n\nPiecesOS: 11.3.3 - Pieces for Developers: 4.1.1\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nHey all,\nPieces Copilot no longer responds in conversations in the app, or through any of the extensions (VS Code/Chrome). It just keeps loading. I've tried hard-resetting, restarting, reinstalling, On-Device LLMs, and Cloud LLMs. The weird thing is, some of the conversations will have a summary or will update the name of the conversation, but it never responds in the chat. I looked at the logs and saw repeated Sentry Event Errors, but not sure what to do with that.  I attached the log file from the day before yesterday (yesterday's is too large and won't upload). What should I do?\n\nThanks!\n\n[log-04292025.txt](https://github.com/user-attachments/files/19997109/log-04292025.txt)\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 4.74
        }
      ]
    },
    {
      "title": "Pieces Copilot not responding or generating output",
      "description": "Users report Pieces Copilot not responding in conversations within the app or extensions (VS Code, Chrome).  Symptoms include continuous loading, lack of responses in chat, and potential Sentry Event Errors in logs.  Some conversation summaries or name updates may still function.  Issue affects Windows and macOS, across various Pieces OS and extension versions.  Troubleshooting steps like resets, restarts, reinstalls, and switching between On-Device/Cloud LLMs have been unsuccessful.  Additionally, the Pieces plugin for Visual Studio may interfere with the Diagnostic tools output, resulting in a blank pane during debugging.",
      "frequency": 3,
      "related_issues": [
        {
          "id": 697,
          "title": "Visual Studio 2022 extension interfering with Diagnostic tool output",
          "text": "Visual Studio 2022 extension interfering with Diagnostic tool output\n### Checked for Existing Issues?\n\n- [x] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application, Visual Studio\n\n### Operating System / Platform\n\nWindows\n\n### Your Pieces OS Version\n\nPiecesOS 11.3.3\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nThe Diagnostic tools pane that, by default, opens when you begin debugging in Visual Studio ends up entirely blank with the Pieces plugin enabled in Visual Studio Version 17.14.0 Preview 4.0. Disabling the plugin restores the Diagnostic tools output.\n\n<img width=\"166\" alt=\"Image\" src=\"https://github.com/user-attachments/assets/beb0d90f-7544-4f26-9516-8e4165b782ce\" />\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 3.74
        },
        {
          "id": 701,
          "title": "Copilot not responding",
          "text": "Copilot not responding\n### Checked for Existing Issues?\n\n- [x] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nWindows\n\n### Your Pieces OS Version\n\nPiecesOS: 11.3.3 - Pieces for Developers: 4.1.1\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nHey all,\nPieces Copilot no longer responds in conversations in the app, or through any of the extensions (VS Code/Chrome). It just keeps loading. I've tried hard-resetting, restarting, reinstalling, On-Device LLMs, and Cloud LLMs. The weird thing is, some of the conversations will have a summary or will update the name of the conversation, but it never responds in the chat. I looked at the logs and saw repeated Sentry Event Errors, but not sure what to do with that.  I attached the log file from the day before yesterday (yesterday's is too large and won't upload). What should I do?\n\nThanks!\n\n[log-04292025.txt](https://github.com/user-attachments/files/19997109/log-04292025.txt)\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 4.74
        },
        {
          "id": 584,
          "title": "Copilot is not giving any feedback",
          "text": "Copilot is not giving any feedback\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nmacOS\n\n### Your Pieces OS Version\n\nPieces for Developers 3.3.3\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nThe copilot is not generating anything, it just keeps on loading.\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 2.84
        }
      ]
    },
    {
      "title": "Pieces for Developers and OS connection issues",
      "description": "Users are experiencing connection issues between Pieces for Developers and Pieces OS on Linux and macOS.  Problems include invalid port errors, login failures with HTTP 500 errors, and Copilot failing to provide feedback.  Check Pieces OS logs for error messages and ensure proper port configuration. Verify Pieces for Developers and OS compatibility.",
      "frequency": 3,
      "related_issues": [
        {
          "id": 641,
          "title": "Invalid port http://0.0.0.0:null/connect",
          "text": "Invalid port http://0.0.0.0:null/connect\n### Checked for Existing Issues?\n\n- [x] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nLinux\n\n### Your Pieces OS Version\n\n3.3.8 2025-02-17\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nPieces for Developers hangs on first run in third step (Verify Dependency Connections) with error message\n\nunable to open Pieces Core Services\nformatexception: Invalid port (at character 16)\nhttp://0.0.0.0:null/connect\n\nPieces OS seems to work fine, for a brief moment I can see its window with information that the service is active on some port. Then window closes - it is impossible to bring it back, but icon in the  system tray is still there.\n\nHow can I set proper port value for Pieces for Developer, and what is the default port value?\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 2.94
        },
        {
          "id": 691,
          "title": "OS: login does not work ( /os/sign_in HTTP 500)",
          "text": "OS: login does not work ( /os/sign_in HTTP 500)\n### Checked for Existing Issues?\n\n- [x] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application, Pieces OS\n\n### Operating System / Platform\n\nLinux\n\n### Your Pieces OS Version\n\n11.3.3\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nWhen I try to log in via PFD, the spinner loads indefinitely before opening an error page in the browser:\n\nhttps://pieces.app/authentication-error?sentry_id=00000000000000000000000000000000&os=bb009f04-7e79-44cb-8376-aba647cd2c98&platform=linux\n\nIn the OS logs (Documents/com.pieces.os/Support/logs) I see this entry:\n\n```\n[D]  2025-04-17T15:53:02.391819  0:00:01.425625 POST    [500] /os/sign_in: port:39300\n```\n\nIt is surrounded by HTTP 200s like this:\n\n```\n[D]  2025-04-17T15:52:53.075570  0:00:00.000685 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:52:54.038635  0:00:00.001700 POST    [200] /websites/exists: port:39300\n[D]  2025-04-17T15:52:54.043187  0:00:00.000732 GET     [200] /.well-known/version: port:39300\n[D]  2025-04-17T15:52:54.335453  0:00:00.001876 POST    [200] /websites/exists: port:39300\n[D]  2025-04-17T15:52:56.077590  0:00:00.000695 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:52:59.079649  0:00:00.000662 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:53:02.081551  0:00:00.000486 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:53:02.391819  0:00:01.425625 POST    [500] /os/sign_in: port:39300\n[D]  2025-04-17T15:53:04.272493  0:00:00.001839 POST    [200] /websites/exists: port:39300\n[D]  2025-04-17T15:53:04.334258  0:00:00.000938 GET     [200] /.well-known/version: port:39300\n[D]  2025-04-17T15:53:04.457128  0:00:00.001378 POST    [200] /websites/exists: port:39300\n[D]  2025-04-17T15:53:05.083569  0:00:00.000541 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:53:08.085902  0:00:00.000518 GET     [200] /.well-known/version: port:39301\n[D]  2025-04-17T15:53:08.094713  0:00:00.001812 POST    [200] /websites/exists: port:39300\n```\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 4.2
        },
        {
          "id": 584,
          "title": "Copilot is not giving any feedback",
          "text": "Copilot is not giving any feedback\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nmacOS\n\n### Your Pieces OS Version\n\nPieces for Developers 3.3.3\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nThe copilot is not generating anything, it just keeps on loading.\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 2.84
        }
      ]
    },
    {
      "title": "Issues with LLM Download and Functionality",
      "description": "Users are experiencing problems with LLM interaction, including an inability to cancel downloads on Windows, installation failures of locally hosted models on Linux, and unresponsiveness/loading issues with Copilot on macOS.  Further investigation is needed to determine the root cause and potential solutions across different operating systems and LLM types.",
      "frequency": 3,
      "related_issues": [
        {
          "id": 459,
          "title": "Bug: unable to cancel the download of an LLLM",
          "text": "Bug: unable to cancel the download of an LLLM\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nWindows\n\n### Your Pieces OS Version\n\nlatest\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\n![image](https://github.com/user-attachments/assets/6e730898-a168-4571-ab0d-6331c4d389a4)\r\n\r\ni want stop but its not working \r\n\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 2.5
        },
        {
          "id": 700,
          "title": "Issues with local llm models",
          "text": "Issues with local llm models\n### Checked for Existing Issues?\n\n- [ ] Yes, I have checked existing issues and cannot find one related to this.\n\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nLinux\n\n### Your Pieces OS Version\n\n11.3.3\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\n![Image](https://github.com/user-attachments/assets/5a5358da-6109-41e2-8ae0-8e2c50e9a2b6)\n\nPieces will not let me install locally hosted models.\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 3.88
        },
        {
          "id": 584,
          "title": "Copilot is not giving any feedback",
          "text": "Copilot is not giving any feedback\n### Software\n\nDesktop Application\n\n### Operating System / Platform\n\nmacOS\n\n### Your Pieces OS Version\n\nPieces for Developers 3.3.3\n\n### Early Access Program\n\n- [ ] Yes, this is related to an Early Access Program feature.\n\n### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.\n\nThe copilot is not generating anything, it just keeps on loading.\nError generating summary: 404 Publisher Model `projects/pi3c3s-cloud-server/locations/us-east1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions",
          "activity_level": 2.84
        }
      ]
    }
  ],
  "recommendations": [
    "Prioritize resolving Copilot issues (unresponsiveness, loading, and LLM model errors) across Windows, macOS, and Linux, given their high frequency and impact on core functionality.",
    "Investigate and address the root cause of Asana handshake failures and Pieces OS login issues (HTTP 500 errors) on Linux, focusing on potential port conflicts and authentication problems.",
    "Improve LLM management by fixing the LLM download cancellation bug on Windows and ensuring seamless installation of locally hosted models on Linux.",
    "Address the conflict between the Pieces Visual Studio extension and Diagnostic tools output on Windows to enhance the debugging experience.",
    "Review and update documentation regarding port configuration and compatibility between Pieces for Developers and Pieces OS, especially for Linux and macOS users.",
    "Proactively monitor error logs, particularly Sentry events, to identify and address emerging issues quickly.",
    "Consider implementing automated tests to catch issues like Asana handshake failures, login errors, and LLM installation problems before they reach users.",
    "Gather more data on user workflows and pain points to identify areas for improvement in the Pieces ecosystem and prioritize future development efforts based on user needs and impact. "
  ],
  "message": "Daily support report generated successfully."
}